In [1]:
%pip install pandas

Requirement already satisfied: pandas in c:\users\06pc-00\appdata\local\programs\python\python312\lib\site-packages (3.0.1)
Requirement already satisfied: numpy>=1.26.0 in c:\users\06pc-00\appdata\local\programs\python\python312\lib\site-packages (from pandas) (2.4.2)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\06pc-00\appdata\roaming\python\python312\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\users\06pc-00\appdata\local\programs\python\python312\lib\site-packages (from pandas) (2025.3)
Requirement already satisfied: six>=1.5 in c:\users\06pc-00\appdata\roaming\python\python312\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 23.2.1 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [2]:
import pandas as pd

In [3]:
pd.__version__

'3.0.1'

# 📊2-1. 데이터 핸들링 Pandas (1)
- Series  → 1차원 데이터
- DataFrame → 2차원 표 형태 데이터

## ✔ Series란?

- 1차원 배열
- **index + values** 로 구성

In [4]:
data=['2017','2018','2019','2020']
se=pd.Series(data)
se

0    2017
1    2018
2    2019
3    2020
dtype: str

In [5]:
type(data)

list

In [6]:
type(se)

pandas.Series

In [7]:
se.index

RangeIndex(start=0, stop=4, step=1)

In [8]:
se[0]

'2017'

In [9]:
se[3]

'2020'

In [10]:
se[0:3]

0    2017
1    2018
2    2019
dtype: str

# ✔ index 이름과 columns 이름 지정:name

In [11]:
se.name='Year'
se

0    2017
1    2018
2    2019
3    2020
Name: Year, dtype: str

In [12]:
se.index.name='No'
se

No
0    2017
1    2018
2    2019
3    2020
Name: Year, dtype: str

# Series생성시 index지정하기

In [13]:
data=['2017','2018','2019','2020']
se=pd.Series(data,index=['a','b','c','d'])
se

a    2017
b    2018
c    2019
d    2020
dtype: str

In [14]:
se['a']

'2017'

In [15]:
se['a':'b']
#문자열(라벨) 슬라이싱은 끝값이 포함됨

a    2017
b    2018
dtype: str

In [16]:
se.index

Index(['a', 'b', 'c', 'd'], dtype='str')

In [17]:
se.values

<StringArray>
['2017', '2018', '2019', '2020']
Length: 4, dtype: str

In [18]:
se.index=['a', 'b', 'c', 'd']

In [19]:
se.index=list('efgh')
se

e    2017
f    2018
g    2019
h    2020
dtype: str

In [20]:
se['f']

'2018'

In [21]:
se.index.name='번호'
se

번호
e    2017
f    2018
g    2019
h    2020
dtype: str

# ✔ 마스킹(masking) 작업 ⭐ 중요

In [22]:
se>'2018', se[~(se>'2018')],se[se>'2018']

(번호
 e    False
 f    False
 g     True
 h     True
 dtype: bool,
 번호
 e    2017
 f    2018
 dtype: str,
 번호
 g    2019
 h    2020
 dtype: str)

# ✔ Series → DataFrame 변환
- to_frame()메소드 이용

In [23]:
se.name='년도'
se

번호
e    2017
f    2018
g    2019
h    2020
Name: 년도, dtype: str

In [24]:
se.to_frame()

      년도
번호
e   2017
f   2018
g   2019
h   2020

# 4️⃣ DataFrame

## ✔ DataFrame이란?

- 2차원 표 형태
- **index + columns + values**

In [25]:
#딕셔너리-키:값형식으로 만듬
#키는 열의 이름이 됨, 값은 values가 됨, 인덱스는 자동 만들어짐

data={"name":["lee","park","kim","hwang","choi"],
      "score":[100,90,30,40,90],
      "grade":["a","b","c","d"]}
data, type(data)

({'name': ['lee', 'park', 'kim', 'hwang', 'choi'],
  'score': [100, 90, 30, 40, 90],
  'grade': ['a', 'b', 'c', 'd']},
 dict)

In [26]:
data={"name":["lee","park","kim","hwang","choi"],
      "score":[100,90,30,40,90],
      "grade":["a","b","c","d","f"]}

df=pd.DataFrame(data, columns=["name","grade","score"])
df

    name grade  score
0    lee     a    100
1   park     b     90
2    kim     c     30
3  hwang     d     40
4   choi     f     90

In [27]:
df.index, df.columns, df.values
#2차원구조임을 알 수 있다.

(RangeIndex(start=0, stop=5, step=1),
 Index(['name', 'grade', 'score'], dtype='str'),
 array([['lee', 'a', 100],
        ['park', 'b', 90],
        ['kim', 'c', 30],
        ['hwang', 'd', 40],
        ['choi', 'f', 90]], dtype=object))

In [28]:
type(df.values)

numpy.ndarray

In [ ]:
df.shape, df.ndim, df.size
#여기에서 사이즈는 총 데이터 갯수-> 5*3=15

((5, 3), 2, 15)

# ✔ 특정 컬럼 값 추출

In [29]:
df

    name grade  score
0    lee     a    100
1   park     b     90
2    kim     c     30
3  hwang     d     40
4   choi     f     90

In [30]:
df['name']

0      lee
1     park
2      kim
3    hwang
4     choi
Name: name, dtype: str

In [31]:
df['name'].values, df['grade'].values, df['grade'].index

(<StringArray>
 ['lee', 'park', 'kim', 'hwang', 'choi']
 Length: 5, dtype: str,
 <StringArray>
 ['a', 'b', 'c', 'd', 'f']
 Length: 5, dtype: str,
 RangeIndex(start=0, stop=5, step=1))

In [32]:
df['score'].values
#문자와 숫자 값이 다르게 나오는 이유는 pandas문자열은 StringArray확장자타입이라서. 숫자는 왜 array?NUmpy기본타입이라서

array([100,  90,  30,  40,  90])

In [33]:
df.loc[1,'name'],df.loc[2,'score']

('park', np.int64(30))

In [34]:
df.name, df.score, df.grade

(0      lee
 1     park
 2      kim
 3    hwang
 4     choi
 Name: name, dtype: str,
 0    100
 1     90
 2     30
 3     40
 4     90
 Name: score, dtype: int64,
 0    a
 1    b
 2    c
 3    d
 4    f
 Name: grade, dtype: str)

# ✔ DataFrame의 index 설정
- 1.DataFrame생성시index설정

In [35]:
data={"name":["lee","park","kim","hwang","choi"],
      "score":[100,90,30,40,90],
      "grade":["a","b","c","d","f"]}

df=pd.DataFrame(data, index=["lee","park","kim","hwang","choi"])
df=pd.DataFrame(data, colums=["name","grade","score"])
df

TypeError: DataFrame.__init__() got an unexpected keyword argument 'colums'

In [36]:
df=pd.DataFrame(data)
df

    name  score grade
0    lee    100     a
1   park     90     b
2    kim     30     c
3  hwang     40     d
4   choi     90     f

In [37]:
#인덱스 재 설정할 수 있다.
df.index=['lee','park','kim','hwang','choi']
df

        name  score grade
lee      lee    100     a
park    park     90     b
kim      kim     30     c
hwang  hwang     40     d
choi    choi     90     f

In [38]:
df.drop('name', axis=1), df.drop('score',axis=1)

(       score grade
 lee      100     a
 park      90     b
 kim       30     c
 hwang     40     d
 choi      90     f,
         name grade
 lee      lee     a
 park    park     b
 kim      kim     c
 hwang  hwang     d
 choi    choi     f)

In [39]:
df.set_index('grade')
df

        name  score grade
lee      lee    100     a
park    park     90     b
kim      kim     30     c
hwang  hwang     40     d
choi    choi     90     f

In [42]:
data=[['lee',80,'A'],
      ['park',100,'A'],
      ['hwang',19,'B'],
      ['choi',100,'A'],]
df=pd.DataFrame(data,columns=['name','score','grade'])
df

    name  score grade
0    lee     80     A
1   park    100     A
2  hwang     19     B
3   choi    100     A

# DataFrame-> list

In [43]:
df.values.tolist()

[['lee', 80, 'A'], ['park', 100, 'A'], ['hwang', 19, 'B'], ['choi', 100, 'A']]

# DataFrame-> 딕셔너리

In [44]:
df.to_dict()

{'name': {0: 'lee', 1: 'park', 2: 'hwang', 3: 'choi'},
 'score': {0: 80, 1: 100, 2: 19, 3: 100},
 'grade': {0: 'A', 1: 'A', 2: 'B', 3: 'A'}}

In [46]:

data = {
    "name": ["lee","park","kim","hwang","choi"],
    "score": [100,90,30,40,90],
    "grade": ["a","b","c","d","f"]  # 하나 추가
}

df = pd.DataFrame(data)
print(df)

    name  score grade
0    lee    100     a
1   park     90     b
2    kim     30     c
3  hwang     40     d
4   choi     90     f

# NumPy ndarray -> DatatFrame

In [47]:
import numpy as np

In [48]:
array=np.array ([['lee',80,'A'],
                 ['park',100,'A'],
                 ['hwang',19,'B'],
                 ['choi',100,'A'],])
array

array([['lee', '80', 'A'],
       ['park', '100', 'A'],
       ['hwang', '19', 'B'],
       ['choi', '100', 'A']], dtype='<U21')

In [49]:
array.shape

(4, 3)

In [50]:
df=pd.DataFrame(array, columns=['name','score','grade'])
df

    name score grade
0    lee    80     A
1   park   100     A
2  hwang    19     B
3   choi   100     A

# Datatframe->Numpy

In [51]:
arr=df.values
arr

array([['lee', '80', 'A'],
       ['park', '100', 'A'],
       ['hwang', '19', 'B'],
       ['choi', '100', 'A']], dtype=object)

In [52]:
type(arr)

numpy.ndarray

# 컬럼 값이 없는 경우 -> NaN 처리
- NaN= Not a Number

In [ ]:
data = {
    "name": ["lee","park","kim","hwang","choi"],
    "score": [100,90,30,40,90],
    "grade": ["a","b","c","d","f"] 
}

c=['name','grade','score','etc']
df=pd.DataFrame(data,columns=c)
df

    name grade  score  etc
0    lee     a    100  NaN
1   park     b     90  NaN
2    kim     c     30  NaN
3  hwang     d     40  NaN
4   choi     f     90  NaN

In [59]:
# Nan 확인
df.isnull().sum()

name     0
grade    0
score    0
etc      5
dtype: int64