In [1]:
import pandas as pd

In [2]:
data = {
    "name": ["lee","park","kim","hwang","choi"],
    "score": [100,90,30,40,90],
    "grade": ["a","b","c","d","f"]  # 하나 추가
}

df = pd.DataFrame(data)
df

    name  score grade
0    lee    100     a
1   park     90     b
2    kim     30     c
3  hwang     40     d
4   choi     90     f

df["컬럼명"]
df.컬럼명

In [3]:
df.name

0      lee
1     park
2      kim
3    hwang
4     choi
Name: name, dtype: str

In [5]:
#여러컬럼선택

In [12]:
df[["name","score","grade"]]

    name  score grade
0    lee    100     a
1   park     90     b
2    kim     30     c
3  hwang     40     d
4   choi     90     f

In [ ]:
#행슬라이싱

In [ ]:
df[1:3] #1행에서 2행까지 가져오기

   name  score grade
1  park     90     b
2   kim     30     c

In [10]:
df[0:2]

   name  score grade
0   lee    100     a
1  park     90     b

# 2️⃣ loc[] — 명칭(Label) 기반 인덱싱 
-df.loc[행이름, 열이름]

In [13]:
df

    name  score grade
0    lee    100     a
1   park     90     b
2    kim     30     c
3  hwang     40     d
4   choi     90     f

In [21]:
df.loc[0]

name     lee
score    100
grade      a
Name: 0, dtype: object

In [ ]:
#여러행 검색 행을 꼭찝어서 이름을 쓰면 됨
df.loc[[0,1,4]]

   name  score grade
0   lee    100     a
1  park     90     b
4  choi     90     f

In [ ]:
#여러행 검색 범위
#만약 index가 문자인 경우도 정렬된 순서로 범위 슬라이싱이 가능하다. 사전순, sort되어 있어야 한다.
df.loc[0:2]

   name  score grade
0   lee    100     a
1  park     90     b
2   kim     30     c

In [25]:
df.loc[0:2,['score','grade']]
df.loc[[0,2],['score','grade']]

   score grade
0    100     a
2     30     c

## iloc[]-위치기반 인덱싱
- df.iloc[행번호,열번호]
- 0부터 시작
- 정수기반 인덱싱
- 끝값 미포함