## 2-4 결손 데이터 (Missing Data) 처리

In [2]:
import pandas as pd
import numpy as np

In [3]:
data = {'name':['Lee', 'Hwang', 'Kim', 'Choi'],
      'score':[100, 95, 80, 85],
      'grade':['A', 'A', 'B', np.nan]}
df = pd.DataFrame(data)
df

    name  score grade
0    Lee    100     A
1  Hwang     95     A
2    Kim     80     B
3   Choi     85   NaN

### NaN 값을 가진 컬럼 추가

In [4]:
# point열에 NaN추가
df['point'] = np.nan
df

    name  score grade  point
0    Lee    100     A    NaN
1  Hwang     95     A    NaN
2    Kim     80     B    NaN
3   Choi     85   NaN    NaN

In [6]:
df.isna()
# → 주어진 값이 NaN인지 확인

    name  score  grade  point
0  False  False  False   True
1  False  False  False   True
2  False  False  False   True
3  False  False   True   True

In [7]:
df.isnull()

    name  score  grade  point
0  False  False  False   True
1  False  False  False   True
2  False  False  False   True
3  False  False   True   True

### 2️⃣ fillna()
- → NaN 값을 지정한 값으로 채움

In [8]:
df

    name  score grade  point
0    Lee    100     A    NaN
1  Hwang     95     A    NaN
2    Kim     80     B    NaN
3   Choi     85   NaN    NaN

In [9]:
type(df)

pandas.DataFrame

In [12]:
# df.fillna(value=0, inplace=True)
df

# fillna는 모든 컬럼에 같은 값을 넣는다.
# 문자열 컬럼에 숫자를 넣으면 TypeError 발생 가능.

    name  score grade  point
0    Lee    100     A    NaN
1  Hwang     95     A    NaN
2    Kim     80     B    NaN
3   Choi     85   NaN    NaN

In [13]:
df.dtypes

name         str
score      int64
grade        str
point    float64
dtype: object

In [14]:
df.select_dtypes(include='number').columns

Index(['score', 'point'], dtype='str')

In [17]:
num_cols = df.select_dtypes(include='number').columns
df[num_cols] = df[num_cols].fillna(0)

In [18]:
df

    name  score grade  point
0    Lee    100     A    0.0
1  Hwang     95     A    0.0
2    Kim     80     B    0.0
3   Choi     85   NaN    0.0

In [19]:
df['point2'] = [50, 100, 70, np.nan]
df

    name  score grade  point  point2
0    Lee    100     A    0.0    50.0
1  Hwang     95     A    0.0   100.0
2    Kim     80     B    0.0    70.0
3   Choi     85   NaN    0.0     NaN

In [20]:
# - point2 컬럼의 NaN에 평균값으로 채우기
df.fillna(value=df['point2'].mean())

    name  score      grade  point      point2
0    Lee    100          A    0.0   50.000000
1  Hwang     95          A    0.0  100.000000
2    Kim     80          B    0.0   70.000000
3   Choi     85  73.333333    0.0   73.333333

In [ ]:
df['grade'].dtype

#StringDtype → Pandas에서 제공하는 문자열 전용 dtype

In [22]:
df

    name  score grade  point  point2
0    Lee    100     A    0.0    50.0
1  Hwang     95     A    0.0   100.0
2    Kim     80     B    0.0    70.0
3   Choi     85   NaN    0.0     NaN

In [ ]:
df['grade'] = df['grade'].fillna('0')
df

# ✔ dtype 유지 (string)

    name  score grade  point  point2
0    Lee    100     A    0.0    50.0
1  Hwang     95     A    0.0   100.0
2    Kim     80     B    0.0    70.0
3   Choi     85     0    0.0     NaN

### 3) df.dropna()
- → NaN이 포함된 행(또는 열)을 삭제

In [25]:
df

    name  score grade  point  point2
0    Lee    100     A    0.0    50.0
1  Hwang     95     A    0.0   100.0
2    Kim     80     B    0.0    70.0
3   Choi     85     0    0.0     NaN

In [ ]:
# df['point2'] = df['point2'].replace(0, np.nan)
# 0을 NaN으로 치환

In [26]:
df.dropna(how='any')

    name  score grade  point  point2
0    Lee    100     A    0.0    50.0
1  Hwang     95     A    0.0   100.0
2    Kim     80     B    0.0    70.0

In [ ]:
df

#dropna는 뷰이다, 원본데이터가 변하지 않는다.

    name  score grade  point  point2
0    Lee    100     A    0.0    50.0
1  Hwang     95     A    0.0   100.0
2    Kim     80     B    0.0    70.0
3   Choi     85     0    0.0     NaN

In [28]:
df.loc[4, :] = [np.nan, np.nan, np.nan, np.nan, np.nan]
df

    name  score grade  point  point2
0    Lee  100.0     A    0.0    50.0
1  Hwang   95.0     A    0.0   100.0
2    Kim   80.0     B    0.0    70.0
3   Choi   85.0     0    0.0     NaN
4    NaN    NaN   NaN    NaN     NaN

In [29]:
#all, 모두가 결측치 일때
df.dropna(how='all')

    name  score grade  point  point2
0    Lee  100.0     A    0.0    50.0
1  Hwang   95.0     A    0.0   100.0
2    Kim   80.0     B    0.0    70.0
3   Choi   85.0     0    0.0     NaN

In [ ]:
df

# 원본 반영 안됨

    name  score grade  point  point2
0    Lee  100.0     A    0.0    50.0
1  Hwang   95.0     A    0.0   100.0
2    Kim   80.0     B    0.0    70.0
3   Choi   85.0     0    0.0     NaN
4    NaN    NaN   NaN    NaN     NaN