## 📊  2-5 DataFrame 데이터 타입 변환

In [67]:
import pandas as pd
import numpy as np



|함수|설명|주 사용 목적|
|-----|----------|--------|
|astype()|일반 타입 변환|숫자 ↔ 숫자
|pd.to_numeric()|숫자로 변환|문자열 → 숫자
|pd.to_datetime()	|날짜형 변환	|문자열 → 날짜
|pd.to_timedelta()	|시간 간격 변환	|문자열 → 날짜 간격

In [48]:
df = pd.DataFrame({"A": [1, 2, 3],
        "B": [1.0, 2.0, 3.0],
        "C": ["2026-01-01", "2026-01-02","2026-01-03"],
        "D": ["1 days", "2 days", "3 days"],
        "E": ["1", "2", "3"]})

df

   A    B           C       D  E
0  1  1.0  2026-01-01  1 days  1
1  2  2.0  2026-01-02  2 days  2
2  3  3.0  2026-01-03  3 days  3

### 1️⃣ 데이터 타입 확인
- 모든 컬럼의 데이터 타입 확인

In [49]:
df.dtypes

A      int64
B    float64
C        str
D        str
E        str
dtype: object

In [50]:
# 전체 데이터 타입과 Null의 여부 확인가능
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       3 non-null      int64
 1   B       3 non-null      float64
 2   C       3 non-null      str
 3   D       3 non-null      str
 4   E       3 non-null      str
dtypes: float64(1), int64(1), str(3)
memory usage: 252.0 bytes

### 2️⃣ astype() : 기본 타입 변환

In [51]:
# A컬럼의 타입
df['A'].dtype

dtype('int64')

In [52]:
# 컬럼 A의 데이터타입을 실수로 변경
df['A'].astype('float')

0    1.0
1    2.0
2    3.0
Name: A, dtype: float64

In [53]:
df

   A    B           C       D  E
0  1  1.0  2026-01-01  1 days  1
1  2  2.0  2026-01-02  2 days  2
2  3  3.0  2026-01-03  3 days  3

In [54]:
# 컬럼 B의 데이터타입을 정수로 변경
df['B'].astype('int')

0    1
1    2
2    3
Name: B, dtype: int64

In [55]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       3 non-null      int64
 1   B       3 non-null      float64
 2   C       3 non-null      str
 3   D       3 non-null      str
 4   E       3 non-null      str
dtypes: float64(1), int64(1), str(3)
memory usage: 252.0 bytes

-  컬럼 A와 B를 동시에 다른 타입으로 변경

In [56]:
# 두개를 동시에 바꾸고 싶을땐 딕셔너리 형태, 키:값 형식으로 준다.
df_a = df.astype({'A' : float, 'B' : int})
df_a

     A  B           C       D  E
0  1.0  1  2026-01-01  1 days  1
1  2.0  2  2026-01-02  2 days  2
2  3.0  3  2026-01-03  3 days  3

In [57]:
print(df.dtypes)  # 원본 
print("===========")
print(df_a.dtypes)

A      int64
B    float64
C        str
D        str
E        str
dtype: object
===========
A    float64
B      int64
C        str
D        str
E        str
dtype: object

### 3️⃣ pd.to_numeric() : 숫자형으로 변환
-  컬럼 E를 숫자로 변경

In [58]:
df['E'].dtypes

In [59]:
# 숫자로 변환
df_a['E'] = pd.to_numeric(df['E'])
df_a.dtypes

A    float64
B      int64
C        str
D        str
E      int64
dtype: object

### 4️⃣ pd.to_datetime() : 날짜형으로 변환
- 컬럼 C를 datetime으로 변경

In [60]:
df['C']

0    2026-01-01
1    2026-01-02
2    2026-01-03
Name: C, dtype: str

In [61]:
pd.to_datetime(df['C'])

# us = microseconds

0   2026-01-01
1   2026-01-02
2   2026-01-03
Name: C, dtype: datetime64[us]

In [62]:
df_a['C'] = pd.to_datetime(df['C'])
df_a.dtypes

A           float64
B             int64
C    datetime64[us]
D               str
E             int64
dtype: object

### 5️⃣ pd.to_timedelta() : 시간 간격 변환
-  컬럼 D를 timedelta로 변경

In [63]:
df['D']

0    1 days
1    2 days
2    3 days
Name: D, dtype: str

In [64]:
pd.to_timedelta(df["D"])

0   1 days
1   2 days
2   3 days
Name: D, dtype: timedelta64[us]

In [65]:
df_a["D"] = pd.to_timedelta(df["D"])

In [66]:
print(df.dtypes)  # 원본 
print("===========")
print(df_a.dtypes)

A      int64
B    float64
C        str
D        str
E        str
dtype: object
===========
A            float64
B              int64
C     datetime64[us]
D    timedelta64[us]
E              int64
dtype: object