## 2-5 DataFrame 데이터 타입 변환
1) astype() : float64, float32, int64, int32의 데이터 타입으로 변환
2) pd.to_numeric(), pd.to_datetime(), pd.to_timedelta()

#### 📌 정리표

|함수|	설명|	주 사용 목적|
|---------------|----------------|-------------------|
|astype()	|일반 타입 변환	|숫자 ↔ 숫자
|pd.to_numeric()	|숫자로 변환 |문자열 → 숫자
|pd.to_datetime()	|날짜형 변환	|문자열 → 날짜
|pd.to_timedelta()	|시간 간격 변환	|문자열 → 날짜 간격

In [1]:
import pandas as pd

In [77]:
df = pd.DataFrame({'A': [1, 2, 3],
                  'B': [1.0, 2.0, 3.0],
                  'C': ['2026-01-01', '2026-01-02', '2026-01-03'],
                  'D' : ['1 days', '2 days', '3 days'],
                  'E': ['1', '2', '3']})
df

   A    B           C       D  E
0  1  1.0  2026-01-01  1 days  1
1  2  2.0  2026-01-02  2 days  2
2  3  3.0  2026-01-03  3 days  3

## 1️⃣ 모든 컬럼의 데이타 타입 확인

In [78]:
df.dtypes

A      int64
B    float64
C        str
D        str
E        str
dtype: object

In [ ]:
# 컬럼	데이터 타입	의미
# A	int64	정수형
# B	float64	실수형
# C	str	문자열 (날짜처럼 보임)
# D	str	문자열 (timedelta처럼 보임)
# E	str	숫자처럼 보이는 문자열

In [79]:
#전체 데이터 타입과 Null의 여부 확인가능
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       3 non-null      int64
 1   B       3 non-null      float64
 2   C       3 non-null      str
 3   D       3 non-null      str
 4   E       3 non-null      str
dtypes: float64(1), int64(1), str(3)
memory usage: 252.0 bytes

## 2️⃣ astype() : 기본 타입 변환

In [ ]:
# 📌 사용 가능 타입
# - `int64`, `int32`
# - `float64`, `float32`
# - `str`

In [80]:
#A컬럼의 타입
df['A'].dtype

dtype('int64')

In [81]:
# 컬럼 A의 데이타타입을 실수로 변경 
df['A'].astype('float')

# ✔ float으로 "변환된 결과"를 만들긴 함
# ❌ 하지만 df에 저장하지 않음

0    1.0
1    2.0
2    3.0
Name: A, dtype: float64

In [82]:
df

#출력은 그대로:
# 👉 변환된 새 객체를 만들고
# 👉 그냥 버린 것과 같음

   A    B           C       D  E
0  1  1.0  2026-01-01  1 days  1
1  2  2.0  2026-01-02  2 days  2
2  3  3.0  2026-01-03  3 days  3

In [66]:
#📌 제대로 바꾸려면, 다시 저장해야 한다.

# df['A'] = df['A'].astype('float')
# 아래 예제에서 동시에 저장할 예정 이므로 그냥 pass

In [83]:
df

   A    B           C       D  E
0  1  1.0  2026-01-01  1 days  1
1  2  2.0  2026-01-02  2 days  2
2  3  3.0  2026-01-03  3 days  3

In [84]:
# 컬럼 B의 데이타타입을 정수로 변경
df['B'].astype(int)

0    1
1    2
2    3
Name: B, dtype: int64

In [85]:
df

   A    B           C       D  E
0  1  1.0  2026-01-01  1 days  1
1  2  2.0  2026-01-02  2 days  2
2  3  3.0  2026-01-03  3 days  3

In [86]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       3 non-null      int64
 1   B       3 non-null      float64
 2   C       3 non-null      str
 3   D       3 non-null      str
 4   E       3 non-null      str
dtypes: float64(1), int64(1), str(3)
memory usage: 252.0 bytes

### 🔹 컬럼 A와 B를 동시에 다른 데이타 타입으로 변경

In [87]:
#두개를 동시에 바꾸고 싶을땐 딕셔너리 형태,  키:값 형식으로 준다.
df_a = df.astype({'A' : float, 'B' : 'int64'})
df_a.dtypes

# ✔ 여러 컬럼을 동시에 변경 가능
# ✔ 딕셔너리 형태로 지정
# df 전체를 복사해서  A, B만 타입 변경한 새 DataFrame 생성, 원본 df는 그대로

# 노션교안
# df[["A", "B"]] = df[["A", "B"]].astype({"A": "float32", "B": "int32"})
# 원본데이터에서 일부 컬럼만 바꾸는 경우, df가 수정됨

A    float64
B      int64
C        str
D        str
E        str
dtype: object

In [89]:
print(df.dtypes)   # 원본
print("=========")
print(df_a.dtypes) # 변경본

A      int64
B    float64
C        str
D        str
E        str
dtype: object
=========
A    float64
B      int64
C        str
D        str
E        str
dtype: object

## 3️⃣ pd.to_numeric() : 숫자형으로 변환

### 🔹 컬럼 E를 숫자로 변경

In [90]:
df

   A    B           C       D  E
0  1  1.0  2026-01-01  1 days  1
1  2  2.0  2026-01-02  2 days  2
2  3  3.0  2026-01-03  3 days  3

In [ ]:
df['E'].dtypes

In [92]:
#숫자로 변환
pd.to_numeric(df['E'])

0    1
1    2
2    3
Name: E, dtype: int64

In [96]:
# df_a의 E컬럼 타입 수정 후 저장
df_a['E'] = pd.to_numeric(df['E'])

In [95]:
df_a.dtypes

A    float64
B      int64
C        str
D        str
E      int64
dtype: object

## 4️⃣ pd.to_datetime() : 날짜형으로 변환

### 🔹 컬럼 C를 datetime으로 변경

In [97]:
df['C']

0    2026-01-01
1    2026-01-02
2    2026-01-03
Name: C, dtype: str

In [101]:
pd.to_datetime(df['C'])

#us = microseconds (마이크로초)
#✔ 이제 날짜 연산 가능
# ✔ 정렬, 차이 계산 가능

0   2026-01-01
1   2026-01-02
2   2026-01-03
Name: C, dtype: datetime64[us]

In [102]:
df_a['C'] = pd.to_datetime(df['C'])

## 5️⃣ pd.to_timedelta() : 시간 간격 변환

### 🔹 컬럼 D를 timedelta로 변경

In [103]:
df['D']

0    1 days
1    2 days
2    3 days
Name: D, dtype: str

In [104]:
pd.to_timedelta(df['D'])

0   1 days
1   2 days
2   3 days
Name: D, dtype: timedelta64[us]

In [105]:
df_a['D'] = pd.to_timedelta(df['D'])

In [106]:
print(df.dtypes)
print("=======")
print(df_a.dtypes)

A      int64
B    float64
C        str
D        str
E        str
dtype: object
=======
A            float64
B              int64
C     datetime64[us]
D    timedelta64[us]
E              int64
dtype: object

In [ ]:
# # 💡 핵심 포인트

# ✔ astype()는 이미 변환 가능한 데이터일 때 사용
# ✔ 문자열 → 숫자는 `to_numeric()`이 안전
# ✔ 날짜 데이터는 반드시 `datetime`으로 변환해야 분석 가능
# ✔ timedelta는 "날짜 간격"