## 📊 2-6  Pandas 데이터프레임 합치기 & 피벗테이블
### 1️⃣ 여러 개의 데이터프레임 합치기
- Pandas에서 여러 DataFrame을 합치는 방법은 크게 2가지입니다.

    - pd.concat() → 단순 연결
    - merge() → 공통 컬럼 기준 JOIN

In [128]:
import pandas as pd
import numpy as np

In [129]:
df1 = pd.DataFrame({
    "이름": ["철수", "영희"],
    "점수": [90, 80]
})

df2 = pd.DataFrame({
    "이름": ["민수", "지영"],
    "점수": [85, 95]
})

In [130]:
df1

   이름  점수
0  철수  90
1  영희  80

In [131]:
df2

   이름  점수
0  민수  85
1  지영  95

### 📌 1-1) pd.concat() : 행 기준 합치기 (axis=0)

- 👉 위아래로 붙이기

- 👉 기본값 `axis=0`

In [132]:
pd.concat([df1,df2],axis=0)

   이름  점수
0  철수  90
1  영희  80
0  민수  85
1  지영  95

In [133]:
# 인덱스 재정렬
result = pd.concat([df1,df2],axis=0,ignore_index=True)
result

   이름  점수
0  철수  90
1  영희  80
2  민수  85
3  지영  95

### 📌 1-2) pd.concat() : 열 기준 합치기 (axis=1)

In [134]:
df3 = pd.DataFrame({
    "학년": [1, 2]
})
df3

   학년
0   1
1   2

In [135]:
# df1,df3 합치기(좌,우로 붙이기)
pd.concat([df1,df3],axis=1)

   이름  점수  학년
0  철수  90   1
1  영희  80   2

### # 📌 1-3) merge() : 공통 컬럼 기준 JOIN

- 👉 SQL JOIN과 동일
- how 옵션 - inner,left,right,outer

In [136]:
member_df = pd.DataFrame({
    "고객번호": [1001, 1002, 1003, 1004, 1005],
    "이름": ["철수", "영희", "혜진", "도윤", "신우"]
})
member_df

   고객번호  이름
0  1001  철수
1  1002  영희
2  1003  혜진
3  1004  도윤
4  1005  신우

In [137]:
transaction_df = pd.DataFrame({
                    "고객번호": [1001, 1001, 1002, 1005, 1006],
                    "금액": [1000, 2000, 1500, 500, 700]
})
transaction_df

   고객번호    금액
0  1001  1000
1  1001  2000
2  1002  1500
3  1005   500
4  1006   700

- ✔ inner join
    - how = 'inner'
    - 공통 데이터만

In [138]:
pd.merge(member_df,transaction_df,how='inner')

   고객번호  이름    금액
0  1001  철수  1000
1  1001  철수  2000
2  1002  영희  1500
3  1005  신우   500

In [139]:
pd.merge(member_df,transaction_df,how='left')

# member_df가 기준이므로 1006번 고객은 나오지 않는다.

   고객번호  이름      금액
0  1001  철수  1000.0
1  1001  철수  2000.0
2  1002  영희  1500.0
3  1003  혜진     NaN
4  1004  도윤     NaN
5  1005  신우   500.0

In [140]:
pd.merge(member_df,transaction_df,how='right')

# transaction_df를 기준으로 하므로 1003,1004 cnffurehlwl dksgdma
# 1006번은 고객번호 등록이 되지 않았으므로 NaN으로 처리됨

   고객번호   이름    금액
0  1001   철수  1000
1  1001   철수  2000
2  1002   영희  1500
3  1005   신우   500
4  1006  NaN   700

- ✔ outer join
    - how = 'outer'
    - 전체 포함, 없는 값은 NaN

In [141]:
pd.merge(member_df,transaction_df,how='outer')

   고객번호   이름      금액
0  1001   철수  1000.0
1  1001   철수  2000.0
2  1002   영희  1500.0
3  1003   혜진     NaN
4  1004   도윤     NaN
5  1005   신우   500.0
6  1006  NaN   700.0

### 2️⃣ 피봇 테이블 (Pivot Table)
- 데이터 열 중 두 개의 열을 각각 행 인덱스, 열 인덱스로 사용하여 데이터를 펼쳐놓은 것
- pivot 메서드
    - 첫번째 인수 : 행 인덱스로 사용할 열 이름
    - 두번째 인수 : 열 인덱스로 사용할 열 이름
    - 마지막 인수 : 데이터로 사용할 열 이름
    - 만약 주어진 데이터가 존재하지 않으면 해당 칸에 NaN 값을 넣는다.
- df.pivot(index, columns, values)

- 📌 예제 데이터
    - 각 도시별 인구

In [142]:
df = pd.DataFrame({
    "도시": ["서울", "서울", "서울", "부산", "부산", "부산", "인천", "인천"],
    "연도": ["2015", "2010", "2005", "2015", "2010", "2005", "2015", "2010"],
    "인구": [9904312, 9631482, 9762546, 3448737, 3393191, 3512547, 2890451, 2632030],
    "지역": ["수도권", "수도권", "수도권", "경상권", "경상권", "경상권", "수도권", "수도권"]
})
df

   도시    연도       인구   지역
0  서울  2015  9904312  수도권
1  서울  2010  9631482  수도권
2  서울  2005  9762546  수도권
3  부산  2015  3448737  경상권
4  부산  2010  3393191  경상권
5  부산  2005  3512547  경상권
6  인천  2015  2890451  수도권
7  인천  2010  2632030  수도권

- 어떤 도시의 어떤 시점의 인구 파악하기 위해 pivot테이블로 변경
    - 행 인덱스 : "연도", 열 인덱스 : "도시", 데이터 이름 : "인구"

In [143]:
df.pivot(index="연도", columns="도시", values="인구")

도시           부산         서울         인천
연도
2005  3512547.0  9762546.0        NaN
2010  3393191.0  9631482.0  2632030.0
2015  3448737.0  9904312.0  2890451.0

In [144]:
df2 = df.pivot(index="연도", columns="도시", values="인구")
df2.fillna(0)

도시           부산         서울         인천
연도
2005  3512547.0  9762546.0        0.0
2010  3393191.0  9631482.0  2632030.0
2015  3448737.0  9904312.0  2890451.0

In [145]:
df.pivot(index="연도", columns="도시", values="인구").fillna(0)

도시           부산         서울         인천
연도
2005  3512547.0  9762546.0        0.0
2010  3393191.0  9631482.0  2632030.0
2015  3448737.0  9904312.0  2890451.0

### 3️⃣ pivot_table() 사용하여 결측치 처리

## 📌 pivot과 pivot_table 차이

| 구분 | pivot | pivot_table |
| --- | --- | --- |
| 중복 데이터 | ❌ 에러 발생 | ✅ 집계 가능 |
| 집계 함수 | 없음 | 있음 (mean, sum 등) |
| 결측치 처리 | NaN 그대로 | fill_value 사용 가능 |
| 실무 사용도 | 낮음 | ⭐⭐⭐⭐⭐ |

- 📌 예제 데이터

In [146]:
df1 = pd.DataFrame({
    "이름": ["철수", "철수", "영희", "영희", "영희"],
    "과목": ["수학", "영어", "수학", "영어", "수학"],
    "점수": [90, 85, 80, 95, 70]
})
df1
# 영희는 수학 점수가 2개 (중복 존재)

   이름  과목  점수
0  철수  수학  90
1  철수  영어  85
2  영희  수학  80
3  영희  영어  95
4  영희  수학  70

In [147]:
# # 중복 데이터
# df1.pivot(index="이름", columns="과목", values="점수")

# ValueError: Index contains duplicate entries, cannot reshape

In [148]:
pd.pivot_table(df1,index="이름",columns="과목",values="점수")
# df1.pivot_table(index="이름",columns="과목",values="점수")

## 기본 집계 함수 = mean
# 영희 수학 점수 (80, 70) → 평균 75

과목    수학    영어
이름
영희  75.0  95.0
철수  90.0  85.0

In [149]:
df.pivot_table(index="연도",columns="도시",values="인구")

도시           부산         서울         인천
연도
2005  3512547.0  9762546.0        NaN
2010  3393191.0  9631482.0  2632030.0
2015  3448737.0  9904312.0  2890451.0

In [150]:
# fill_value - 결측치 대체
df.pivot_table(index="연도",
               columns="도시",
               values="인구",
               aggfunc="sum",
               fill_value=0)

도시         부산       서울       인천
연도
2005  3512547  9762546        0
2010  3393191  9631482  2632030
2015  3448737  9904312  2890451

In [151]:
df3 = pd.DataFrame({
    "도시": ["서울", "서울", "서울", "부산", "부산", "부산", "인천", "인천","서울"],
    "연도": ["2015", "2010", "2005", "2015", "2010", "2005", "2015", "2010","2015"],
    "인구": [9904312, 9631482, 9762546, 3448737, 3393191, 3512547, 2890451, 2632030,2564589],
    "지역": ["수도권", "수도권", "수도권", "경상권", "경상권", "경상권", "수도권", "수도권","수도권"]
})
df3

   도시    연도       인구   지역
0  서울  2015  9904312  수도권
1  서울  2010  9631482  수도권
2  서울  2005  9762546  수도권
3  부산  2015  3448737  경상권
4  부산  2010  3393191  경상권
5  부산  2005  3512547  경상권
6  인천  2015  2890451  수도권
7  인천  2010  2632030  수도권
8  서울  2015  2564589  수도권

In [152]:
df3.pivot_table(index="연도",
               columns="도시",
               values="인구",
               aggfunc="sum",
               fill_value=0)

도시         부산        서울       인천
연도
2005  3512547   9762546        0
2010  3393191   9631482  2632030
2015  3448737  12468901  2890451

In [153]:
df3.pivot_table(index="연도",
               columns="도시",
               values="인구",
               fill_value=0)

도시           부산         서울         인천
연도
2005  3512547.0  9762546.0        0.0
2010  3393191.0  9631482.0  2632030.0
2015  3448737.0  6234450.5  2890451.0