## 📘 Pandas 종합 연습문제 2

In [184]:
import pandas as pd
import numpy as np

### 문제 1

다음 DataFrame을 생성하세요.

In [185]:
data = {
    "A": ["1", "2", "3"],
    "B": [10, 20, 30],
    "C": ["2026-01-01", "2026-01-02", "2026-01-03"],
    "D": ["1 days", "2 days", "3 days"]
}
df = pd.DataFrame(data)
df

   A   B           C       D
0  1  10  2026-01-01  1 days
1  2  20  2026-01-02  2 days
2  3  30  2026-01-03  3 days

In [186]:
df.dtypes

A      str
B    int64
C      str
D      str
dtype: object

- ① A 컬럼을 정수형으로 변환하세요.

In [187]:
df_a = df
df_a["A"] = pd.to_numeric(df["A"])
df_a.dtypes

A    int64
B    int64
C      str
D      str
dtype: object

- ② C 컬럼을 datetime 형으로 변환하세요.

In [188]:
df_a["C"] = pd.to_datetime(df["C"])
df_a.dtypes

A             int64
B             int64
C    datetime64[us]
D               str
dtype: object

- ③ D 컬럼을 timedelta 형으로 변환하세요.

In [189]:
df_a["D"] = pd.to_timedelta(df["D"])
df_a.dtypes

A              int64
B              int64
C     datetime64[us]
D    timedelta64[us]
dtype: object

- ④ 모든 컬럼의 dtype을 출력하세요.

In [190]:
df_a.dtypes

A              int64
B              int64
C     datetime64[us]
D    timedelta64[us]
dtype: object

### 문제 2

A 컬럼을 float로 변환했는데 출력이 `1,2,3`으로 나옵니다.

왜 그런지 설명하세요.

In [191]:
df["A"].astype(float)
df

# 아마 변경한 값을 df에 집어넣지 않은게 아닐까 싶은데

   A   B          C      D
0  1  10 2026-01-01 1 days
1  2  20 2026-01-02 2 days
2  3  30 2026-01-03 3 days

### 문제 3

다음 두 DataFrame을 생성하세요.

In [192]:
df1 = pd.DataFrame({
    "이름" : ["철수","영희"],
    "점수" : [90,80]
})

df2 = pd.DataFrame({
    "이름" : ["민수","지영"],
    "점수" : [85,95]
})
df1

   이름  점수
0  철수  90
1  영희  80

In [193]:
df2

   이름  점수
0  민수  85
1  지영  95

- ① 두 DataFrame을 행 기준으로 합치세요.

In [194]:
pd.concat([df1,df2],axis=0)

   이름  점수
0  철수  90
1  영희  80
0  민수  85
1  지영  95

- ② 인덱스를 0부터 다시 정렬하세요.

In [195]:
pd.concat([df1,df2],axis=0,ignore_index=True)

   이름  점수
0  철수  90
1  영희  80
2  민수  85
3  지영  95

### 문제 4

다음 DataFrame을 생성하세요.

In [196]:
df1 = pd.DataFrame({"이름" : [],"점수" : []})

df3 = pd.DataFrame({"학년" : []})
df1

Empty DataFrame
Columns: [이름, 점수]
Index: []

In [197]:
df3

Empty DataFrame
Columns: [학년]
Index: []

- ① 열 기준으로 합치세요.

In [198]:
pd.concat([df1,df3],axis=1)

Empty DataFrame
Columns: [이름, 점수, 학년]
Index: []

- ② axis=0과 axis=1의 차이를 설명하세요.

In [199]:
# 0은 행 기준으로 통합=> 열이 통합됨 열의 index값이 바뀜
# 1은 열 기준으로 통합=> 행이 통합됨 행의 index값이 바뀜

### 문제 5

다음 두 DataFrame을 생성하세요.

In [200]:
# df_student
# 이름  학번
# 철수   1
# 영희   2
# 민수   3

# df_score
# 학번  점수
# 1    90
# 2    80
# 4   100
df_student = pd.DataFrame({
    "이름" : ["철수","영희","민수"],
    "학번" : [1,2,3]
})

df_score = pd.DataFrame({
    "학번" : [1,2,4],
    "점수" : [90,50,100],
})

df_student

   이름  학번
0  철수   1
1  영희   2
2  민수   3

In [201]:
df_score

   학번   점수
0   1   90
1   2   50
2   4  100

- ① inner join 결과를 출력하세요.

In [202]:
pd.merge(df_student,df_score,how='inner')

   이름  학번  점수
0  철수   1  90
1  영희   2  50

- ② outer join 결과를 출력하세요.

In [203]:
pd.merge(df_student,df_score,how='outer')

    이름  학번     점수
0   철수   1   90.0
1   영희   2   50.0
2   민수   3    NaN
3  NaN   4  100.0

- ③ inner와 outer의 차이를 설명하세요.

In [204]:
# inner은 공통된값만 가져오고 공통되지 않은값은 사라지게한다.
# outer은 공통되지 않은 값 포함 전부 가져온다.

### 문제 6

다음 데이터를 생성하세요.

In [205]:
df = pd.DataFrame({
    "이름" : ["철수","철수","영희","영희"],
    "과목" : ["수학","영어","수학","영어"],
    "점수" : [90,50,100],
})
df

ValueError: All arrays must be of the same length

- ① pivot을 사용하여 행=이름, 열=과목, 값=점수로 재구성하세요.

### 문제 7

다음 데이터를 생성하세요.

In [ ]:
# 이름   과목   점수
# 철수   수학   90
# 철수   수학   80
# 영희   영어   95

- ① pivot을 사용하면 왜 에러가 발생하는지 설명하세요.

- ② pivot_table을 사용하여 평균값으로 출력하세요.

- ③ NaN을 0으로 채우세요.

### 문제 8

In [ ]:
#    이름  점수
# 0  철수  90
# 1  영희  80

- ① DataFrame을 ex.csv로 저장하세요.

- ② 인덱스를 제외하고 저장하세요.

- ③ 다시 읽어서 출력하세요.

### 문제 9

지금 현재 df , 아래 출력과 같지 않으면 다시 생성한다.

In [ ]:
# 이름	점수
# 0	철수	90
# 1	영희	80

- ① DataFrame을 ex.xlsx 로 저장하세요.(index는 제외)

- ② 시트 이름을 `"1반"`으로 지정하세요.(ex1.xlsx,  index는 제외)

- ③ 두 개의 DataFrame을 서로 다른 시트에 동시에 저장하세요.(ex2.xlsx, index는 제외)

- 시트이름은 1반, 2반으로 하시오.

### 문제 10

다음 중 어떤 상황에서 merge를 사용해야 하는지 설명하세요.

- 같은 구조의 데이터를 위아래로 붙일 때
- 학번을 기준으로 학생 정보와 점수를 합칠 때
- 데이터를 행과 열로 재구성할 때

### 문제 11

상대경로로 `dream.txt`를 열었는데 에러가 발생했습니다.

가능한 원인을 설명하세요.