# 🎓 머신러닝 종합 실습 문제

## 📊 문제 1 타이타닉 생존 예측
- 다음 데이터를 사용하여 타이타닉 승객의 생존 여부를 예측하는 모델을 만들어보시오.

In [78]:
import seaborn as sns

df = sns.load_dataset("titanic")

## 문제 1 데이터 탐색

다음 항목을 확인하시오.

1️⃣ 데이터의 행과 열의 구조

In [79]:
df.shape

(891, 15)

2️⃣ 각 컬럼의 데이터 타입

In [80]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   survived     891 non-null    int64
 1   pclass       891 non-null    int64
 2   sex          891 non-null    str
 3   age          714 non-null    float64
 4   sibsp        891 non-null    int64
 5   parch        891 non-null    int64
 6   fare         891 non-null    float64
 7   embarked     889 non-null    str
 8   class        891 non-null    category
 9   who          891 non-null    str
 10  adult_male   891 non-null    bool
 11  deck         203 non-null    category
 12  embark_town  889 non-null    str
 13  alive        891 non-null    str
 14  alone        891 non-null    bool
dtypes: bool(2), category(2), float64(2), int64(4), str(5)
memory usage: 80.7 KB

3️⃣ 결측치 개수 확인

In [81]:
# df.isna().sum()
df.isnull().sum()

survived         0
pclass           0
sex              0
age            177
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64

## 문제 2 데이터 전처리

다음 변수만 사용하여 모델을 생성하시오.

In [82]:
# pclass
# sex
# age
# fare
# embarked

In [83]:
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [84]:
df[['pclass','sex','age','fare','embarked', 'survived']]

     pclass     sex   age     fare embarked  survived
0         3    male  22.0   7.2500        S         0
1         1  female  38.0  71.2833        C         1
2         3  female  26.0   7.9250        S         1
3         1  female  35.0  53.1000        S         1
4         3    male  35.0   8.0500        S         0
..      ...     ...   ...      ...      ...       ...
886       2    male  27.0  13.0000        S         0
887       1  female  19.0  30.0000        S         1
888       3  female   NaN  23.4500        S         0
889       1    male  26.0  30.0000        C         1
890       3    male  32.0   7.7500        Q         0

[891 rows x 6 columns]

In [85]:
import pandas as pd

titanic = df[['pclass','sex','age','fare','embarked', 'survived']].copy()

#결측치 처리
titanic['age']= titanic['age'].fillna(titanic['age'].median())
titanic['embarked'] = titanic['embarked'].fillna(titanic['embarked'].mode()[0])

#독립변수, 종속변수 분리
X = titanic.drop('survived', axis=1)
y = titanic['survived']

#범주형(문자) 변수 변환
X = pd.get_dummies(X, drop_first=True)

X.head()

   pclass   age     fare  sex_male  embarked_Q  embarked_S
0       3  22.0   7.2500      True       False        True
1       1  38.0  71.2833     False       False       False
2       3  26.0   7.9250     False       False        True
3       1  35.0  53.1000     False       False        True
4       3  35.0   8.0500      True       False        True

In [86]:
titanic.tail()

     pclass     sex   age   fare embarked  survived
886       2    male  27.0  13.00        S         0
887       1  female  19.0  30.00        S         1
888       3  female  28.0  23.45        S         0
889       1    male  26.0  30.00        C         1
890       3    male  32.0   7.75        Q         0

In [87]:
titanic['age'].median()

np.float64(28.0)

In [88]:
titanic['embarked'].mode()[0]

'S'

## 문제 3 데이터 분할

데이터를 **학습용 데이터와 테스트 데이터**로 분할하시오.

In [89]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [90]:
y_test

709    1
439    0
840    0
720    1
39     1
      ..
433    0
773    0
25     1
84     1
10     1
Name: survived, Length: 179, dtype: int64

## 문제 4 모델 생성

다음 모델을 사용하여 학습을 수행하시오.

- Logistic Regression(모델 학습 반복 횟수 1000, 랜덤값 고정 42)
- Decision Tree(랜덤값 고정 42)
- Random Forest(랜덤값 고정 42)

In [91]:
from sklearn.linear_model import LogisticRegression
from sklearn.tree import  DecisionTreeClassifier
from sklearn.ensemble import  RandomForestClassifier

lr = LogisticRegression(max_iter=1000, random_state=42)
dt = DecisionTreeClassifier(random_state=42)
rf = RandomForestClassifier(random_state=42)

lr.fit(X_train, y_train)
dt.fit(X_train, y_train)
rf.fit(X_train, y_train)

RandomForestClassifier(random_state=42)

## 문제 5 모델 평가

각 모델의 **정확도(accuracy)**를 출력하고 비교하시오.(반올림)

In [92]:
lr_pred = lr.predict(X_test)
dt_pred = dt.predict(X_test)
rf_pred = rf.predict(X_test)

In [93]:
lr.score(X_test, y_test)

0.7988826815642458

In [94]:
# 예측한 값 비교 
print("모델이 예측한 값 : ", lr_pred[:5])
print("정답 :", y_test.values[:5])

모델이 예측한 값 :  [0 0 0 1 1]
정답 : [1 0 0 1 1]

In [95]:
from sklearn.metrics import accuracy_score
print("Logistic Regression :", round(accuracy_score(y_test, lr_pred), 4))
print("Decision Tree       :", round(accuracy_score(y_test, dt_pred), 4))
print("Random Forest       :", round(accuracy_score(y_test, rf_pred), 4))

Logistic Regression : 0.7989
Decision Tree       : 0.7654
Random Forest       : 0.7989

## 문제 6 혼동 행렬

가장 성능이 좋은 모델을 선택하여

**혼동 행렬(confusion matrix)**을 출력하시오.

In [96]:
from sklearn.metrics import  confusion_matrix
cm = confusion_matrix(y_test, rf_pred)
cm

array([[86, 19],
       [17, 57]])

In [97]:
# [[TN FP]
#  [FN TP]]

# - TN(True Negative) : 실제 0, 예측 0  => 86
# - FP(False Positive) : 실제 0, 예측 1  => 19
# - FN(False Negative) : 실제 1, 예측 0  => 17
# - TP(True Positive) 맞게 맞춘 경우 (양성) : 실제 1, 예측 1  => 57

## 문제 7 중요 변수 확인

Random Forest 모델을 사용하여

**가장 중요한 변수(feature)**를 확인하시오.

In [98]:
rf.feature_importances_

array([0.09461079, 0.28142161, 0.31177781, 0.28028642, 0.00879055,
       0.02311283])

In [99]:
importance = pd.Series(rf.feature_importances_, index=X.columns)
print(importance.sort_values(ascending=False))

fare          0.311778
age           0.281422
sex_male      0.280286
pclass        0.094611
embarked_S    0.023113
embarked_Q    0.008791
dtype: float64

In [100]:
lr.coef_

array([[-1.00594150e+00, -2.46096331e-02,  3.61662294e-04,
        -2.45928526e+00, -1.00020785e-01, -5.13978741e-01]])

In [101]:
import pandas as pd

importance = pd.Series(lr.coef_[0], index=X.columns)
importance.sort_values(ascending=False)

fare          0.000362
age          -0.024610
embarked_Q   -0.100021
embarked_S   -0.513979
pclass       -1.005942
sex_male     -2.459285
dtype: float64

In [102]:
# feature_importances_는 트리 기반 모델 전용(얼만나 분할에 기여했는지?)
# Decision Tree, Random Forest

# Logistic Regression
# 계수 크기, coef_, 방향성 있음 (+/-)

In [103]:
# 질문 : CatBoostClassifier 사용하여 분류
import seaborn as sns
from catboost import CatBoostClassifier
from sklearn.model_selection import train_test_split

df = sns.load_dataset("titanic")

titanic = df[['pclass','sex','age','fare','embarked', 'survived']].copy()

#결측치 처리
titanic['age']= titanic['age'].fillna(titanic['age'].median())
titanic['embarked'] = titanic['embarked'].fillna(titanic['embarked'].mode()[0])

#독립변수, 종속변수 분리
X = titanic.drop('survived', axis=1)
y = titanic['survived']

cat_features = ['sex', 'embarked']

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

model = CatBoostClassifier(verbose=0, random_state=42)

model.fit(X_train, y_train, cat_features=cat_features)

print(model.score(X_test, y_test))

0.7988826815642458

In [104]:
model.feature_importances_

array([20.61698097, 40.28633369, 15.49931603, 13.41933004, 10.17803927])

In [105]:
import pandas as pd

importances = pd.Series(model.feature_importances_, index=X.columns)
importances.sort_values(ascending=False)

sex         40.286334
pclass      20.616981
age         15.499316
fare        13.419330
embarked    10.178039
dtype: float64

In [106]:
# RandomForest는 “얼마나 자주 썼는지”
# CatBoost는 “얼마나 도움이 됐는지”를 본다

# 👉 모델이 다르면 중요도 기준도 다르다 → 값이 달라지는 건 정상

# 2. 와인 분류 모델

### 문제 1 데이터 확인

다음 항목을 확인하시오.

- 데이터의 shape
- 클래스 개수
- feature 이름

In [107]:
from sklearn.datasets import load_wine
import pandas as pd
import numpy as np

In [108]:
wine = load_wine()
wine

{'data': array([[1.423e+01, 1.710e+00, 2.430e+00, ..., 1.040e+00, 3.920e+00,
         1.065e+03],
        [1.320e+01, 1.780e+00, 2.140e+00, ..., 1.050e+00, 3.400e+00,
         1.050e+03],
        [1.316e+01, 2.360e+00, 2.670e+00, ..., 1.030e+00, 3.170e+00,
         1.185e+03],
        ...,
        [1.327e+01, 4.280e+00, 2.260e+00, ..., 5.900e-01, 1.560e+00,
         8.350e+02],
        [1.317e+01, 2.590e+00, 2.370e+00, ..., 6.000e-01, 1.620e+00,
         8.400e+02],
        [1.413e+01, 4.100e+00, 2.740e+00, ..., 6.100e-01, 1.600e+00,
         5.600e+02]], shape=(178, 13)),
 'target': array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2]),
 'frame': None,
 'target_names': array(['class_0', 'class_1', 'class_2'], dtype='<U7'),
 'DESCR': '.. _wine_dataset:\n\nWine recognition dataset\n------------------------\n\n**Data Set Characteristics:**\n\n:Number of Instances: 178\n:Number of Attributes: 13 numeric, predictive attributes and the class\n:Attribute Information:\n    - Alcohol\n    - Malic acid\n    - Ash\n    - Alcalinity of ash\n    - Magnesium\n    - Total phenols\n    - Flavanoids\n    - Nonflavanoid phenols\n    - Proanthocyanins\n    - Color intensity\n    - Hue\n    - OD280/OD315 of diluted wines\n    - Proline\n    - class:\n        - class_0\n        - class_1\n        - class_2\n\n:Summary Statistics:\n\n============================= ==== ===== ======= =====\n                                Min   Max   Mean     SD\n============================= ==== ===== ======= =====\nAlcohol:                      11.0  14.8    13.0   0.8\nMalic Acid:                   0.74  5.80    2.34  1.12\nAsh:                          1.36  3.23    2.36  0.27\nAlcalinity of Ash:            10.6  30.0    19.5   3.3\nMagnesium:                    70.0 162.0    99.7  14.3\nTotal Phenols:                0.98  3.88    2.29  0.63\nFlavanoids:                   0.34  5.08    2.03  1.00\nNonflavanoid Phenols:         0.13  0.66    0.36  0.12\nProanthocyanins:              0.41  3.58    1.59  0.57\nColour Intensity:              1.3  13.0     5.1   2.3\nHue:                          0.48  1.71    0.96  0.23\nOD280/OD315 of diluted wines: 1.27  4.00    2.61  0.71\nProline:                       278  1680     746   315\n============================= ==== ===== ======= =====\n\n:Missing Attribute Values: None\n:Class Distribution: class_0 (59), class_1 (71), class_2 (48)\n:Creator: R.A. Fisher\n:Donor: Michael Marshall (MARSHALL%PLU@io.arc.nasa.gov)\n:Date: July, 1988\n\nThis is a copy of UCI ML Wine recognition datasets.\nhttps://archive.ics.uci.edu/ml/machine-learning-databases/wine/wine.data\n\nThe data is the results of a chemical analysis of wines grown in the same\nregion in Italy by three different cultivators. There are thirteen different\nmeasurements taken for different constituents found in the three types of\nwine.\n\nOriginal Owners:\n\nForina, M. et al, PARVUS -\nAn Extendible Package for Data Exploration, Classification and Correlation.\nInstitute of Pharmaceutical and Food Analysis and Technologies,\nVia Brigata Salerno, 16147 Genoa, Italy.\n\nCitation:\n\nLichman, M. (2013). UCI Machine Learning Repository\n[https://archive.ics.uci.edu/ml]. Irvine, CA: University of California,\nSchool of Information and Computer Science.\n\n.. dropdown:: References\n\n    (1) S. Aeberhard, D. Coomans and O. de Vel,\n    Comparison of Classifiers in High Dimensional Settings,\n    Tech. Rep. no. 92-02, (1992), Dept. of Computer Science and Dept. of\n    Mathematics and Statistics, James Cook University of North Queensland.\n    (Also submitted to Technometrics).\n\n    The data was used with many others for comparing various\n    classifiers. The classes are separable, though only RDA\n    has achieved 100% correct classification.\n    (RDA : 100%, QDA 99.4%, LDA 98.9%, 1NN 96.1% (z-transformed data))\n    (All results using the leave-one-out technique)\n\n    (2) S. Aeberhard, D. Coomans and O. de Vel,\n    "THE CLASSIFICATION PERFORMANCE OF RDA"\n    Tech. Rep. no. 92-01, (1992), Dept. of Computer Science and Dept. of\n    Mathematics and Statistics, James Cook University of North Queensland.\n    (Also submitted to Journal of Chemometrics).\n',
 'feature_names': ['alcohol',
  'malic_acid',
  'ash',
  'alcalinity_of_ash',
  'magnesium',
  'total_phenols',
  'flavanoids',
  'nonflavanoid_phenols',
  'proanthocyanins',
  'color_intensity',
  'hue',
  'od280/od315_of_diluted_wines',
  'proline']}

In [109]:
type(wine)

#"사이킷런 번치 객체"
# 즉 딕셔너리처럼 여러 데이터를 묶어놓은 객체입니다.

sklearn.utils._bunch.Bunch

In [110]:
wine.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names'])

In [111]:
# data -> 입력 데이터 (X)
# target -> 정답 (y)
wine.feature_names

['alcohol',
 'malic_acid',
 'ash',
 'alcalinity_of_ash',
 'magnesium',
 'total_phenols',
 'flavanoids',
 'nonflavanoid_phenols',
 'proanthocyanins',
 'color_intensity',
 'hue',
 'od280/od315_of_diluted_wines',
 'proline']

In [112]:
wine.target_names

array(['class_0', 'class_1', 'class_2'], dtype='<U7')

In [113]:
X = pd.DataFrame(wine.data, columns=wine.feature_names)
y = wine.target

In [114]:
print(X.shape)  #데이터 크기 확인
print(np.unique(y))  #클래스 종류 확인
print(X.columns)  #feature 이름 확인

(178, 13)
[0 1 2]
Index(['alcohol', 'malic_acid', 'ash', 'alcalinity_of_ash', 'magnesium',
       'total_phenols', 'flavanoids', 'nonflavanoid_phenols',
       'proanthocyanins', 'color_intensity', 'hue',
       'od280/od315_of_diluted_wines', 'proline'],
      dtype='str')

## 문제 2 데이터 스케일링

데이터를 **StandardScaler**를 사용하여 스케일링 하시오.

In [115]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

## 문제 3 모델 생성

다음 모델을 사용하여 학습하시오.

- KNN
- SVM (Support Vector Machine) - SVC
- RandomForest

In [116]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier

# SVM (Support Vector Machine) :  알고리즘 이름
# SVC, SVR, LinearSVC => 클래스이름

# SVC (Support Vector Classifier) - 분류 (Classification)
# SVR - 회귀 (Regression)
# LinearSVC - 선형 SVM (빠른 버전)

In [117]:
knn = KNeighborsClassifier() # random요소가 없음 가까운 k개의 요소를 찾는다.
svm = SVC()
rf = RandomForestClassifier(random_state=42)

In [118]:
knn.fit(X_train_scaled, y_train)
svm.fit(X_train_scaled, y_train)
rf.fit(X_train, y_train)   #스케일링 영향이 적어서 원본 사용 가능

RandomForestClassifier(random_state=42)

## 문제 4 성능 비교

각 모델의 정확도를 비교하시오.

In [119]:
from sklearn.metrics import accuracy_score

knn_pred = knn.predict(X_test_scaled)
svm_pred = svm.predict(X_test_scaled)
rf_pred = rf.predict(X_test)

In [120]:
svm_pred[:5]

array([0, 2, 0, 1, 1])

In [121]:
print("KNN          :", round(accuracy_score(y_test, knn_pred), 4))
print("SVM          :", round(accuracy_score(y_test, svm_pred), 4))
print("RandomForest :", round(accuracy_score(y_test, rf_pred), 4))

KNN          : 0.9722
SVM          : 0.9722
RandomForest : 1.0

# 📊 문제 3 모델 평가 지표

In [122]:
from sklearn.datasets import load_breast_cancer
from sklearn.linear_model import LogisticRegression

cancer = load_breast_cancer()
cancer

{'data': array([[1.799e+01, 1.038e+01, 1.228e+02, ..., 2.654e-01, 4.601e-01,
         1.189e-01],
        [2.057e+01, 1.777e+01, 1.329e+02, ..., 1.860e-01, 2.750e-01,
         8.902e-02],
        [1.969e+01, 2.125e+01, 1.300e+02, ..., 2.430e-01, 3.613e-01,
         8.758e-02],
        ...,
        [1.660e+01, 2.808e+01, 1.083e+02, ..., 1.418e-01, 2.218e-01,
         7.820e-02],
        [2.060e+01, 2.933e+01, 1.401e+02, ..., 2.650e-01, 4.087e-01,
         1.240e-01],
        [7.760e+00, 2.454e+01, 4.792e+01, ..., 0.000e+00, 2.871e-01,
         7.039e-02]], shape=(569, 30)),
 'target': array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
        0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
        1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
        1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
        1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0,
        0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1,
        1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0,
        0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0,
        1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1,
        1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0,
        0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0,
        0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0,
        1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1,
        1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1,
        1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0,
        1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1,
        1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1,
        1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1]),
 'frame': None,
 'target_names': array(['malignant', 'benign'], dtype='<U9'),
 'DESCR': '.. _breast_cancer_dataset:\n\nBreast cancer Wisconsin (diagnostic) dataset\n--------------------------------------------\n\n**Data Set Characteristics:**\n\n:Number of Instances: 569\n\n:Number of Attributes: 30 numeric, predictive attributes and the class\n\n:Attribute Information:\n    - radius (mean of distances from center to points on the perimeter)\n    - texture (standard deviation of gray-scale values)\n    - perimeter\n    - area\n    - smoothness (local variation in radius lengths)\n    - compactness (perimeter^2 / area - 1.0)\n    - concavity (severity of concave portions of the contour)\n    - concave points (number of concave portions of the contour)\n    - symmetry\n    - fractal dimension ("coastline approximation" - 1)\n\n    The mean, standard error, and "worst" or largest (mean of the three\n    worst/largest values) of these features were computed for each image,\n    resulting in 30 features.  For instance, field 0 is Mean Radius, field\n    10 is Radius SE, field 20 is Worst Radius.\n\n    - class:\n            - WDBC-Malignant\n            - WDBC-Benign\n\n:Summary Statistics:\n\n===================================== ====== ======\n                                        Min    Max\n===================================== ====== ======\nradius (mean):                        6.981  28.11\ntexture (mean):                       9.71   39.28\nperimeter (mean):                     43.79  188.5\narea (mean):                          143.5  2501.0\nsmoothness (mean):                    0.053  0.163\ncompactness (mean):                   0.019  0.345\nconcavity (mean):                     0.0    0.427\nconcave points (mean):                0.0    0.201\nsymmetry (mean):                      0.106  0.304\nfractal dimension (mean):             0.05   0.097\nradius (standard error):              0.112  2.873\ntexture (standard error):             0.36   4.885\nperimeter (standard error):           0.757  21.98\narea (standard error):                6.802  542.2\nsmoothness (standard error):          0.002  0.031\ncompactness (standard error):         0.002  0.135\nconcavity (standard error):           0.0    0.396\nconcave points (standard error):      0.0    0.053\nsymmetry (standard error):            0.008  0.079\nfractal dimension (standard error):   0.001  0.03\nradius (worst):                       7.93   36.04\ntexture (worst):                      12.02  49.54\nperimeter (worst):                    50.41  251.2\narea (worst):                         185.2  4254.0\nsmoothness (worst):                   0.071  0.223\ncompactness (worst):                  0.027  1.058\nconcavity (worst):                    0.0    1.252\nconcave points (worst):               0.0    0.291\nsymmetry (worst):                     0.156  0.664\nfractal dimension (worst):            0.055  0.208\n===================================== ====== ======\n\n:Missing Attribute Values: None\n\n:Class Distribution: 212 - Malignant, 357 - Benign\n\n:Creator:  Dr. William H. Wolberg, W. Nick Street, Olvi L. Mangasarian\n\n:Donor: Nick Street\n\n:Date: November, 1995\n\nThis is a copy of UCI ML Breast Cancer Wisconsin (Diagnostic) datasets.\nhttps://goo.gl/U2Uwz2\n\nFeatures are computed from a digitized image of a fine needle\naspirate (FNA) of a breast mass.  They describe\ncharacteristics of the cell nuclei present in the image.\n\nSeparating plane described above was obtained using\nMultisurface Method-Tree (MSM-T) [K. P. Bennett, "Decision Tree\nConstruction Via Linear Programming." Proceedings of the 4th\nMidwest Artificial Intelligence and Cognitive Science Society,\npp. 97-101, 1992], a classification method which uses linear\nprogramming to construct a decision tree.  Relevant features\nwere selected using an exhaustive search in the space of 1-4\nfeatures and 1-3 separating planes.\n\nThe actual linear program used to obtain the separating plane\nin the 3-dimensional space is that described in:\n[K. P. Bennett and O. L. Mangasarian: "Robust Linear\nProgramming Discrimination of Two Linearly Inseparable Sets",\nOptimization Methods and Software 1, 1992, 23-34].\n\nThis database is also available through the UW CS ftp server:\n\nftp ftp.cs.wisc.edu\ncd math-prog/cpo-dataset/machine-learn/WDBC/\n\n.. dropdown:: References\n\n  - W.N. Street, W.H. Wolberg and O.L. Mangasarian. Nuclear feature extraction\n    for breast tumor diagnosis. IS&T/SPIE 1993 International Symposium on\n    Electronic Imaging: Science and Technology, volume 1905, pages 861-870,\n    San Jose, CA, 1993.\n  - O.L. Mangasarian, W.N. Street and W.H. Wolberg. Breast cancer diagnosis and\n    prognosis via linear programming. Operations Research, 43(4), pages 570-577,\n    July-August 1995.\n  - W.H. Wolberg, W.N. Street, and O.L. Mangasarian. Machine learning techniques\n    to diagnose breast cancer from fine-needle aspirates. Cancer Letters 77 (1994)\n    163-171.\n',
 'feature_names': array(['mean radius', 'mean texture', 'mean perimeter', 'mean area',
        'mean smoothness', 'mean compactness', 'mean concavity',
        'mean concave points', 'mean symmetry', 'mean fractal dimension',
        'radius error', 'texture error', 'perimeter error', 'area error',
        'smoothness error', 'compactness error', 'concavity error',
        'concave points error', 'symmetry error',
        'fractal dimension error', 'worst radius', 'worst texture',
        'worst perimeter', 'worst area', 'worst smoothness',
        'worst compactness', 'worst concavity', 'worst concave points',
        'worst symmetry', 'worst fractal dimension'], dtype='<U23'),
 'filename': 'breast_cancer.csv',
 'data_module': 'sklearn.datasets.data'}

In [123]:
X = pd.DataFrame(cancer.data, columns=cancer.feature_names)
y = cancer.target

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

- Logistic Regression으로 학습

In [124]:
lr = LogisticRegression(max_iter=10000, random_state=42)
lr.fit(X_train_scaled, y_train)

pred = lr.predict(X_test_scaled)

평가 지표 계산

In [125]:
from sklearn.metrics import classification_report, precision_score, recall_score, f1_score

acc = accuracy_score(y_test, pred)
prec = precision_score(y_test, pred)
rec = recall_score(y_test, pred)
f1 = f1_score(y_test, pred)
print("accuracy :", round(acc, 4))
print("precision:", round(prec, 4))
print("recall   :", round(rec, 4))
print("f1-score :", round(f1, 4))

accuracy : 0.9825
precision: 0.9861
recall   : 0.9861
f1-score : 0.9861

In [126]:
# accuracy : 전체 중 맞춘 비율
# precision : 양성이라고 예측한 것 중 실제 양성 비율
# recall : 실제 양성 중 찾아낸 비율
# f1-score : precision과 recall의 조화평균

In [127]:
print(classification_report(y_test, pred, digits=4))

              precision    recall  f1-score   support

           0     0.9762    0.9762    0.9762        42
           1     0.9861    0.9861    0.9861        72

    accuracy                         0.9825       114
   macro avg     0.9812    0.9812    0.9812       114
weighted avg     0.9825    0.9825    0.9825       114

In [ ]:
# precision(정밀도)  recall(재현율) f1-score(정밀도와 재현율의 조화 평균) support(실제데이터개수)
# macro avg : 각 클래스 성능 평균, => 계산 방법 (클래스0 + 클래스1) / 2
# weighted avg 데이터 개수 기준 평균 => 계산 방법 클래스별 성능 × 데이터 개수
# (0.9762*42 + 0.9861*72) / 114  = 0.9825

# 📊 문제 4 모델 성능 개선

유방암 데이터셋을 사용하여 모델 성능을 개선하시오.

### 문제 1 RandomForest 모델 생성

RandomForest 모델을 생성하고 학습하시오.

In [129]:
from sklearn.ensemble import RandomForestClassifier

rf = RandomForestClassifier(random_state=42)
rf.fit(X_train, y_train)

RandomForestClassifier(random_state=42)

In [131]:
from sklearn.model_selection import cross_validate
score = cross_validate(rf, X_train,y_train, return_train_score=True)
score

{'fit_time': array([0.19351077, 0.17652845, 0.17453432, 0.17151618, 0.19550323]),
 'score_time': array([0.00994682, 0.00995517, 0.00900364, 0.01296258, 0.01196814]),
 'test_score': array([0.96703297, 0.98901099, 0.92307692, 0.93406593, 0.95604396]),
 'train_score': array([1., 1., 1., 1., 1.])}

In [132]:
# 훈련세트점수
np.mean(score['train_score'])

np.float64(1.0)

In [133]:
#테스트점수(cross_validate test_score)
np.mean(score['test_score'])

np.float64(0.953846153846154)

In [134]:
# 최종 테스트
rf.score(X_test, y_test)

0.956140350877193

### 문제 2 하이퍼파라미터 튜닝

GridSearchCV를 사용하여 다음 파라미터를 튜닝하시오.

In [135]:
from sklearn.model_selection import GridSearchCV

param_grid = {
    'n_estimators': [100, 200, 300],
    'max_depth': [None, 3, 5, 10]
}

grid = GridSearchCV(
    RandomForestClassifier(random_state=42),
    param_grid=param_grid,
    scoring='recall'  # 재현율 기준으로 가장 좋은 모델 선택
)

grid.fit(X_train, y_train)

GridSearchCV(estimator=RandomForestClassifier(random_state=42),
             param_grid={'max_depth': [None, 3, 5, 10],
                         'n_estimators': [100, 200, 300]},
             scoring='recall')

In [ ]:
score = cross_validate(grid, X_train,y_train, return_train_score=True)
score

{'fit_time': array([20.12523055, 20.19002843, 19.31038213, 19.62750673, 19.80605817]),
 'score_time': array([0.01194239, 0.01795411, 0.01296186, 0.01196742, 0.01196814]),
 'test_score': array([0.98245614, 1.        , 0.96491228, 0.94736842, 0.94736842]),
 'train_score': array([1., 1., 1., 1., 1.])}

In [137]:
#테스트점수(cross_validate test_score)
np.mean(score['test_score'])

np.float64(0.968421052631579)

In [138]:
# 훈련데이터
np.mean(score['train_score'])

np.float64(1.0)

In [ ]:
# 최종 테스트
grid.score(X_test, y_test)

0.9722222222222222

## 문제 3 최적 파라미터 출력

다음 항목을 출력하시오.

- best_params_
- best_score_

In [ ]:
grid.best_params_

# None :   트리의 깊이를 제한하지 않는다

{'max_depth': None, 'n_estimators': 100}

In [ ]:
grid.best_score_
# 교차검증(cross validation)에서 나온 validation score의 평균

np.float64(0.968421052631579)

In [144]:
best_model  = grid.best_estimator_

### 문제 4 중요 변수 확인

모델에서 가장 중요한 변수 **상위 5개**를 출력하시오.

In [145]:
best_model.feature_importances_

array([0.06867599, 0.00958431, 0.06957388, 0.04917215, 0.00559816,
       0.01171465, 0.05763806, 0.09088475, 0.00466601, 0.00448887,
       0.01677021, 0.00521386, 0.0096331 , 0.03310446, 0.00349852,
       0.00597922, 0.00431035, 0.00409824, 0.00401198, 0.00444169,
       0.09769574, 0.01859665, 0.07222637, 0.14001599, 0.0124362 ,
       0.01860002, 0.03434013, 0.12952961, 0.00833452, 0.00516632])

In [146]:
importances = pd.Series(best_model.feature_importances_, index=X.columns)
importances.sort_values(ascending=False).head(5)

worst area              0.140016
worst concave points    0.129530
worst radius            0.097696
mean concave points     0.090885
worst perimeter         0.072226
dtype: float64

In [ ]:
# 이 모델에서 유방암 분류에 가장 중요한 변수 TOP5
# worst area  면적이 가장 큰값
# worst concave points 오목한 부분의 개수
# worst radius  종양반지름 가장 큰값
# mean concave points 오목한 부분의 평균값
# worst perimeter 종양 둘레 가장 큰값